//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyrsovayaRabota
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KyrsovayaRabotaDBEntities1 : DbContext
    {
        public static KyrsovayaRabotaDBEntities1 _context;

        public static KyrsovayaRabotaDBEntities1 getContext()
        {
            if (_context == null)
                _context = new KyrsovayaRabotaDBEntities1();
            return _context;
        }
        public KyrsovayaRabotaDBEntities1()
            : base("name=KyrsovayaRabotaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DET> DET { get; set; }
        public virtual DbSet<SE> SE { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
        public virtual DbSet<Table_2> Table_2 { get; set; }
        public virtual DbSet<Table_3> Table_3 { get; set; }
        public virtual DbSet<UZ> UZ { get; set; }
    }
}
