//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyrsovayaRabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DET()
        {
            this.Details_In_SESet = new HashSet<Details_In_SESet>();
        }
    
        public string CodeDET { get; set; }
        public string NameDET { get; set; }
        public double b { get; set; }
        public double y { get; set; }
        public double da { get; set; }
        public double a1 { get; set; }
        public double n1 { get; set; }
        public double n2 { get; set; }
        public double z1 { get; set; }
        public double z2 { get; set; }
        public double C1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_In_SESet> Details_In_SESet { get; set; }
    }
}
